- name: configuring catalogue component
  hosts: catalogue 
  become: yes
  tasks: 
  - name: Disabling default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling nodejs:20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: create roboshop system user
    ansible.builtin.user: 
      name: roboshop
      shell: /sbin/nologin
      system: true 
      home: /app

  - name: download the catalogue command_result
    ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
    dest: /tmp/catalogue.zip

  # this module thinks file exist on ansible control server, needs to extract on to remote machine
  - name: unzip the zipped catalogue file
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes #yes means file already existed on the catalogue server

  - name: install the dependencies
    community.genral.npm: 
      path: /app

  - name: copy catalogue service file to system directory
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Starting and enabling catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/momgo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  - name: Checking if data is loaded into the catalogue or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print catalogue outcome
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"
      
  - name: Loading data into the catalogue
    ansible.builtin.shell:  mongosh --host mongodb.daws84s.site < /app/db/master-data.js
    when: catalogue_output.stdout | int < 0
