---
- name: Configure frontend component
  hosts: frontend
  become: yes
  vars_files:
  - secrets.yml

  tasks:
    - name: Ensure NodeJS/Nginx module defaults are disabled (idempotent)
      ansible.builtin.yum:
        name: nginx
        state: absent

    - name: Enable nginx:1.24 module
      ansible.builtin.command: dnf module enable nginx:1.24 -y
      args:
        creates: /etc/alternatives/nginx

    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start and enable nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Remove old HTML directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Recreate HTML directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
        owner: nginx
        group: nginx
        mode: '0755'
        
    - name: Download frontend code if not already downloaded
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip
        mode: '0644'

    - name: Extract frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
        owner: nginx
        group: nginx

    - name: Deploy custom nginx config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Reload nginx to apply new configuration
      ansible.builtin.service:
        name: nginx
        state: restarted
