---
- name: configuring mongodb server
  hosts: mongodb
  become: yes
  vars_files:
    - secrets.yml

  tasks:
    - name: Copy mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install mongodb server
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: Start and enable mongodb service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: Enable remote connections for mongodb server
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Restart mongodb
      ansible.builtin.service:
        name: mongod
        state: restarted